name: himl
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.10.0
  - cudatoolkit=11.3.1
  - pip:
      - -r hi-ml-azure/run_requirements.txt
      - -r hi-ml/run_requirements.txt
      - -r build_requirements.txt
      - -r test_requirements.txt
