name: AmuletExample
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - pip=22.2.2
  - python=3.9.13
  - pytorch=1.10.0
  - torchvision=0.10.0
  - pip:
      - azureml-core==1.43.0
      - azureml-dataset-runtime[fuse]==1.43.0
      - azureml-tensorboard==1.43.0
      - azureml-train-core==1.43.0
      - conda-merge==0.1.5
      - msal-extensions==0.3.1
      - pandas==1.3.4
      - param==1.12
      - protobuf==3.20.1
      - pytorch-lightning>=1.6.0, <1.7
      - ruamel.yaml==0.16.12
      - setuptools==59.5.0
      - tensorboard==2.6.0
      - dataclasses-json==0.5.2
      - jinja2==3.0.2
      - matplotlib==3.4.3
      - opencv-python-headless==4.5.1.48
      - pandas==1.3.4
      - protobuf==3.20.1
      - rpdb==0.1.6
