name: CredScan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CredScan:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Credential Scanning
        id: credscan
        uses: microsoft/security-devops-action@v1.5.0
        with:
            policy: Github
            categories: secrets
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.credscan.outputs.sarifFile }}
